# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Jishnu Lav Website"
description:	       "As a computational systems immunology lab, our research focuses on the development and use of novel systems approaches to analyze high-dimensional immunological datasets, and elucidate molecular mechanisms of immunological disorders. We are currently working on using network systems and functional genomic approaches to perform multi-scale integration of genomic and epigenomic datasets with biological networks to identify molecular phenotypes underlying these immunological disorders. We also use statistical and machine-learning techniques to integrate multi-omic datasets (genomic, transcriptomic, proteomic, metabolomic and antibody-omic) and elucidate molecular mechanisms of immune regulation and dysregulation."
author:              "Simar Yadav"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
